### ISSUE TITLE
Build error on FreeBSD

### ISSUE THREAD

**Issue by nokute78** [monkey/monkey#235]
Built error is occurred.
My environment is FreeBSD 10.2 , clang 3.4.1
I used 62f1aa2f01c0e5b668bd3a1b58ab1db4a1460be7

Note: I can build,when WITH_BACKTRACE is No .

## Build log
``` make
[ 65%] Built target monkey-mandril-shared
[ 95%] Built target monkey-core-static
[ 96%] Linking C executable monkey
../mk_server/libmonkey.a(mk_utils.c.o): In function `mk_utils_stacktrace':
monkey/mk_server/mk_utils.c:(.text+0xc4e): undefined reference to `backtrace'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[3]: stopped in monkey/build
*** Error code 1

Stop.
make[2]: stopped in monkey/build
*** Error code 1

Stop.
make[1]: stopped in monkey/build
*** Error code 1

Stop.
make: stopped in monkey
```

**Comment by edsiper** [comment]
thanks for the report. 

I will work in a auto "backtrace" discovery support for the build system. Work in process.

**Comment by edsiper** [comment]
which version are you trying ?, per this commit it should be fixed:

563307d5bc8f5b35231cf41ea5be2fa5d7210a24

**Comment by nokute78** [comment]
Monkey is 1.7.0.
I used 62f1aa2f01c0e5b668bd3a1b58ab1db4a1460be7 
It contains commit 563307d5bc8f5b35231cf41ea5be2fa5d7210a24.

I built with these commands.
``` sh
$ sh ./configure --local
$ make
```

libexecinfo.so.1 and libexecinfo.a are installed at /usr/lib and /usr/lib32.

Hmm...

**Comment by edsiper** [comment]
do you say that I need to link to linkexecinfo.so to get the functionality on FreeBSD ?

**Comment by nokute78** [comment]
No, I only shared my environmental information.(libexecinfo.so/a are already installed.)

I have no idea to fix this issue, but it seems to be environment-dependent.
So, I want to provide environmental information you need if any.

By the way, I tried to add a explicit flag to bottom of CMakeLists.txt.
However, the issue was not fixed.
```
set(CMAKE_C_FLAGS "-lexecinfo")
```

**Comment by edsiper** [comment]
hmm looking at the freebsd manpage the function is there:

https://www.freebsd.org/cgi/man.cgi?query=backtrace&apropos=0&sektion=3&manpath=FreeBSD+11-current&format=html
